export const commercialOrdersPermissions = {
  read: "module.commercial-orders.read",
  quoteCreate: "module.commercial-orders.quote.create",
  quoteEdit: "module.commercial-orders.quote.edit",
  quoteIssue: "module.commercial-orders.quote.issue",
  quoteAccept: "module.commercial-orders.quote.accept",
  quoteDecline: "module.commercial-orders.quote.decline",
  quoteCancel: "module.commercial-orders.quote.cancel",
  quoteRevise: "module.commercial-orders.quote.revise",
  orderCreate: "module.commercial-orders.order.create",
  orderEdit: "module.commercial-orders.order.edit",
  orderConfirm: "module.commercial-orders.order.confirm",
  orderCancel: "module.commercial-orders.order.cancel",
  orderClose: "module.commercial-orders.order.close",
  allocationManage: "module.commercial-orders.allocation.manage",
  fulfillmentCreate: "module.commercial-orders.fulfillment.create",
  fulfillmentEdit: "module.commercial-orders.fulfillment.edit",
  fulfillmentConfirm: "module.commercial-orders.fulfillment.confirm",
  fulfillmentCancel: "module.commercial-orders.fulfillment.cancel",
  shipmentCreate: "module.commercial-orders.shipment.create",
  shipmentEdit: "module.commercial-orders.shipment.edit",
  shipmentShip: "module.commercial-orders.shipment.ship",
  shipmentDeliver: "module.commercial-orders.shipment.deliver",
  shipmentCancel: "module.commercial-orders.shipment.cancel"
} as const;
