import type { ErrorCode } from "@nox-os/contracts";

export type ProcurementProblemCode = Extract<
  ErrorCode,
  | "SUPPLIER_NOT_FOUND"
  | "SUPPLIER_ON_HOLD"
  | "SUPPLIER_ARCHIVED"
  | "SUPPLIER_OFFER_NOT_FOUND"
  | "SUPPLIER_OFFER_MISMATCH"
  | "MATERIAL_NOT_FOUND"
  | "MATERIAL_ACCESS_DENIED"
  | "PURCHASE_ORDER_NOT_FOUND"
  | "PURCHASE_ORDER_NOT_EDITABLE"
  | "PURCHASE_ORDER_NOT_APPROVABLE"
  | "PURCHASE_ORDER_ALREADY_TERMINAL"
  | "PURCHASE_ORDER_HAS_RECEIPTS"
  | "PURCHASE_ORDER_LINE_NOT_FOUND"
  | "GOODS_RECEIPT_NOT_FOUND"
  | "GOODS_RECEIPT_NOT_EDITABLE"
  | "GOODS_RECEIPT_ALREADY_POSTED"
  | "GOODS_RECEIPT_POST_FAILED"
  | "RECEIPT_PO_MISMATCH"
  | "RECEIPT_SUPPLIER_MISMATCH"
  | "RECEIPT_MATERIAL_MISMATCH"
  | "OVER_RECEIPT_NOT_ALLOWED"
  | "INVENTORY_RECEIPT_UNAVAILABLE"
  | "INVENTORY_LOT_IDENTITY_CONFLICT"
  | "INVALID_QUANTITY"
  | "INVALID_PRICE"
  | "INVALID_CURRENCY"
  | "IDEMPOTENCY_CONFLICT"
  | "TENANT_ACCESS_DENIED"
  | "PERMISSION_DENIED"
>;

export class ProcurementProblem extends Error {
  constructor(
    readonly status: number,
    readonly code: ProcurementProblemCode,
    message: string
  ) {
    super(message);
  }
}
